"""Add streak_last_updated to User and remove xp_reward from Quest

Revision ID: 455753a14e76
Revises: 45e222a75bf0
Create Date: 2026-05-15 13:18:33.399853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455753a14e76'
down_revision = '45e222a75bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('xp_reward')
        batch_op.drop_column('streak')
        batch_op.drop_column('xp')
        batch_op.drop_column('last_active')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_last_updated', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('streak_last_updated')

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('xp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('streak', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('xp_reward', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
