"""clean XP and progression system

Revision ID: 45e222a75bf0
Revises: ac24d437ac7a
Create Date: 2026-05-06 20:09:35.604645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e222a75bf0'
down_revision = 'ac24d437ac7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('streak')
        batch_op.drop_column('xp')

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('xp_reward')

    # ### end Alembic commands ###
