"""update User and Quest: add xp and streak fields

Revision ID: ac24d437ac7a
Revises: 60fd383f5a00
Create Date: 2026-05-06 20:01:20.216849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac24d437ac7a'
down_revision = '60fd383f5a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('xp_reward', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('xp_reward')
        batch_op.drop_column('last_active')
        batch_op.drop_column('streak')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
